//! Implementation of [Pokemon Gen (III) Save file data structure](https://bulbapedia.bulbagarden.net/wiki/Save_data_structure_(Generation_III)).
//!
//! The structure consists of 128 KB of data, though not every byte is used. The integrity of most of the file is validated by checksums.
//!
//! # File structure
//!
//! The Generation III save file is broken up into two game save blocks (Game Save A, Game Save B), each of which is broken up into 14 4KB sections.
//!
//! One block of game save data represents the most recent game save, and the other block represents the previous game save.
//!
//!|  Offset  | Size  |   Contents    |
//!|----------|-------|---------------|
//!| 0x000000 | 57344 |  Game save A  |
//!| 0x00E000 | 57344 |  Game save B  |
//!
//! # Section format
//!
//! All sections contain the same general format: 3968 bytes of data, followed by a footer. All 14 sections must be present exactly once in each game save block.
//!
//!| Offset | Size | Contents    |
//!|--------|------|-------------|
//!| 0x0000 | 3968 |  Data       |
//!| 0x0FF4 |   2  |  Section ID |
//!| 0x0FF6 |   2  |  Checksum   |
//!| 0x0FF8 |   4  |  Signature  |
//!| 0x0FFC |   4  |  Save Index |
//!
//! Every time the game is saved the order of the sections gets rotated once.The sections only ever get rotated and never scrambled so they will always remain in the same order, but may begin at different points.
//!
//! ## Checksum
//!
//! Used to validate the integrity of saved data.
//! A 16-bit checksum generated by adding up bytes from the section. The algorithm is as follows:
//! -Initialize a 32-bit checksum variable to zero.
//! -Read 4 bytes at a time as 32-bit word (little-endian) and add it to the variable.
//! -Take the upper 16 bits of the result, and add them to the lower 16 bits of the result.
//! -This new 16-bit value is the checksum.
//!
//! ## Save Index
//!
//! Every time the game is saved, its Save Index value goes up by one. This is true even when starting a new game: it continues to count up from the previous save. All 14 sections within a game save must have the same Save Index value. The most recent game save will have a greater Save Index value than the previous save.
//!
//! # Section ID
//!
//!| ID | Size |    Contents    |
//!|----|------|----------------|
//!| 00 | 3884 |  Trainer info  |
//!| 01 | 3968 |  Team / items  |
//!| 02 | 3968 |   Game State   |
//!| 03 | 3968 |   Misc Data    |
//!| 04 | 3968 |   Rival info   |
//!| 05 | 3968 |  PC buffer A   |
//!| 06 | 3968 |  PC buffer A   |
//!| 07 | 3968 |  PC buffer A   |
//!| 08 | 3968 |  PC buffer A   |
//!| 09 | 3968 |  PC buffer A   |
//!| 10 | 3968 |  PC buffer A   |
//!| 11 | 3968 |  PC buffer A   |
//!| 12 | 3968 |  PC buffer A   |
//!| 13 | 2000 |  PC buffer A   |
//!

// src/save/mod.rs
use crate::common::character_set::{get_char, get_code};
use crate::error::{PokemonError, SaveDataError};
use crate::misc::{find_item, item_id_g3};
use crate::pokemon::{Gender, Pokemon};
use crate::save::storage::{pocket_address, PARTY_COUNT_OFFSET, PARTY_SIZE};
use crate::save::trainer::{TimePlayed, TrainerID};
use byteorder::{ByteOrder, LittleEndian};

// --- Sub-Modules ---
pub mod pc;
pub mod section;
pub mod storage;
pub mod trainer;

use self::pc::PCBuffer;
use self::section::Section;
pub use self::section::SectionID;
use self::storage::{Pocket, StorageType, TEAM_SECTION_ID};
use self::trainer::{GameVersion, GymBadges, Trainer};

// --- Constants ---
const NUMBER_GAME_SAVE_SECTIONS: usize = 14;
const SECTION_SIZE: usize = 0x1000; // 4096 bytes
const GAME_SAVE_A_OFFSET: usize = 0x000000;
const GAME_SAVE_B_OFFSET: usize = 0x00E000;

/// Representation of the Save File.
///
/// The Generation III save file is broken up into two game save blocks (Game Save A, Game Save B),
/// each of which is broken up into 14 4KB sections.
#[derive(Default, Debug, Clone)]
pub struct SaveFile {
    game_save_a: [Section; NUMBER_GAME_SAVE_SECTIONS],
    game_save_b: [Section; NUMBER_GAME_SAVE_SECTIONS],
    pub data: Vec<u8>,
    pc_buffer: PCBuffer,
}

impl SaveFile {
    pub fn new(data: &[u8]) -> Self {
        let mut game_save_a: [Section; NUMBER_GAME_SAVE_SECTIONS] =
            [Section::default(); NUMBER_GAME_SAVE_SECTIONS];
        let mut game_save_b: [Section; NUMBER_GAME_SAVE_SECTIONS] =
            [Section::default(); NUMBER_GAME_SAVE_SECTIONS];

        // Read each game save block, the two sets of 14 game save sections
        for i in 0..NUMBER_GAME_SAVE_SECTIONS {
            let save_a_offset = GAME_SAVE_A_OFFSET + (i * SECTION_SIZE);
            let save_b_offset = GAME_SAVE_B_OFFSET + (i * SECTION_SIZE);

            game_save_a[i] = Section {
                offset: save_a_offset,
                size: SECTION_SIZE,
            };
            game_save_b[i] = Section {
                offset: save_b_offset,
                size: SECTION_SIZE,
            };
        }

        let mut save = SaveFile {
            game_save_a,
            game_save_b,
            data: data.to_vec(),
            pc_buffer: PCBuffer::default(),
        };

        save.init_pc_buffer();

        save
    }

    pub fn is_empty(&self) -> bool {
        self.data.len() == 0
    }

    pub fn ot_name(&self) -> Vec<u8> {
        let section = self
            .get_section(SectionID::TrainerInfo)
            .expect("Expected value but found None");
        let section_data_buffer = section.data(&self.data);

        section_data_buffer[0x0000..7].to_vec()
    }

    pub fn ot_id(&self) -> Vec<u8> {
        let section = self
            .get_section(SectionID::TrainerInfo)
            .expect("Expected value but found None");
        let section_data_buffer = section.data(&self.data);

        section_data_buffer[0x000A..0x000A + 4].to_vec()
    }

    pub fn get_party(&self) -> Result<Vec<Pokemon>, SaveDataError> {
        let game_code = self.get_game_code()?;
        let section = self
            .get_section(SectionID::TeamItems)
            .expect("Expected value but found None");
        let section_data_buffer = section.data(&self.data);

        let mut team: Vec<Pokemon> = vec![];

        if game_code == 0x00000001 {
            for (i, pokemon_data) in section_data_buffer[0x0038..0x0290].chunks(100).enumerate() {
                let offset = section.offset() + 0x0038 + (i * 100);
                let pokemon = Pokemon::from_bytes(offset, pokemon_data)?;
                team.push(pokemon);
            }
        } else {
            for (i, pokemon_data) in section_data_buffer[0x0238..0x0490].chunks(100).enumerate() {
                let offset = section.offset() + 0x0238 + (i * 100);
                let pokemon = Pokemon::from_bytes(offset, pokemon_data)?;
                team.push(pokemon);
            }
        }

        Ok(team)
    }

    pub fn pc_box(&self, number: usize) -> Result<Vec<Pokemon>, PokemonError> {
        self.pc_buffer.pc_box(number)
    }

    pub fn is_pc_empty(&self) -> bool {
        self.pc_buffer.is_empty()
    }

    /// Sets a Pokémon at a specific PC location.
    /// Overwrites whatever was there. Use this for injecting new Pokémon.
    pub fn set_pc_pokemon(
        &mut self,
        box_idx: usize,
        slot_idx: usize,
        pokemon: &Pokemon,
    ) -> Result<(), SaveDataError> {
        // We only take the first 80 bytes (Persistent Data)
        let bytes = pokemon.to_bytes();
        self.pc_buffer
            .write_raw_slot(box_idx, slot_idx, &bytes[..80], &mut self.data)
    }

    pub fn swap_pokemon(
        &mut self,
        mut from: Pokemon,
        from_storage: StorageType,
        mut to: Pokemon,
        to_storage: StorageType,
    ) -> Result<(), SaveDataError> {
        std::mem::swap(&mut from.offset, &mut to.offset);
        self.save_pokemon(to_storage, from)?;
        self.save_pokemon(from_storage, to)?;
        Ok(())
    }

    /// Deletes a Pokémon by overwriting it with zeros.
    pub fn delete_pc_pokemon(
        &mut self,
        box_idx: usize,
        slot_idx: usize,
    ) -> Result<(), SaveDataError> {
        let empty_data = [0u8; 80];
        self.pc_buffer
            .write_raw_slot(box_idx, slot_idx, &empty_data, &mut self.data)
    }

    pub fn save_pokemon(
        &mut self,
        storage: StorageType,
        pokemon: Pokemon,
    ) -> Result<(), SaveDataError> {
        match storage {
            StorageType::Party => {
                let offset = pokemon.offset;

                self.data[offset..offset + 100].copy_from_slice(&pokemon.to_bytes());
                let section = self
                    .get_section(SectionID::TeamItems)
                    .expect("Expected value but found None");
                section.write_checksum(&mut self.data)?;
            }
            StorageType::PC => {
                self.pc_buffer.save_pokemon(pokemon, &mut self.data)?;
            }
            _ => {}
        }
        Ok(())
    }

    /// For Ruby and Sapphire, this value will be 0x00000000.
    /// For FireRed and LeafGreen, this value will be 0x00000001.
    /// For Emerald any value other than 0 or 1 can be used.
    pub fn game_code(&self) -> u32 {
        let section = self
            .get_section(SectionID::TrainerInfo)
            .expect("Expected value but found None");
        let section_data_buffer = section.data(&self.data);
        LittleEndian::read_u32(&section_data_buffer[0x00AC..0x00AC + 4])
    }

    /// The security_key location may vary depending on the game.
    /// --------------------------------------
    /// | Offset | Size | Game |
    /// |   N/A  |  N/A |  RS  |
    /// | 0x00AC |   4  |  RS  |
    /// | 0x0AF8 |   4  | FrLg |
    /// --------------------------------------
    /// Ruby and Sapphire either do not utilize this masking operation, or the mask is always zero.
    fn security_key(&self) -> u32 {
        let game_code = self.game_code();

        if game_code == 0x00000000 {
            0x00000000
        } else if game_code == 0x00000001 {
            let section = self
                .get_section(SectionID::TrainerInfo)
                .expect("Expected value but found None");
            let section_data_buffer = section.data(&self.data);
            LittleEndian::read_u32(&section_data_buffer[0x0AF8..0x0AF8 + 4])
        } else {
            game_code
        }
    }

    fn security_key_lower(&self) -> u16 {
        LittleEndian::read_u16(&self.security_key().to_le_bytes()[..2])
    }

    /// Retrieves the pocket data from the save file.
    ///
    /// Offsets and data encryption vary depending on the game version.
    pub fn pocket(&self, pocket: Pocket) -> Result<Vec<(String, u16)>, SaveDataError> {
        let game_code = self.game_code();
        let (start, end) = pocket_address(pocket, game_code);
        self.read_pocket(start, end)
    }

    /// Saves the updated pocket data back into the save file.
    ///
    /// This function writes the modified pocket data into the corresponding save section,
    /// encrypting it with the security key.
    pub fn save_pocket(
        &mut self,
        pocket_type: Pocket,
        pocket_list: Vec<(String, u16)>,
    ) -> Result<(), SaveDataError> {
        let game_code = self.game_code();
        let security_key = self.security_key_lower();
        let (start, end) = pocket_address(pocket_type, game_code);

        let section = self
            .get_section(SectionID::TeamItems)
            .ok_or(SaveDataError::SectionNotFound(SectionID::TeamItems))?;
        let section_data_buffer: &mut [u8] = section.data_mut(&mut self.data);

        let encrypted_bag = SaveFile::encrypt_pocket(pocket_list, security_key)?;
        section_data_buffer[start..end].copy_from_slice(&encrypted_bag);
        section.write_checksum(&mut self.data)?;

        Ok(())
    }

    fn read_pocket(&self, start: usize, end: usize) -> Result<Vec<(String, u16)>, SaveDataError> {
        let security_key = self.security_key_lower();

        let section = self
            .get_section(SectionID::TeamItems)
            .ok_or(SaveDataError::SectionNotFound(SectionID::TeamItems))?;
        let section_data_buffer = section.data(&self.data);

        let bag = SaveFile::decrypt_pocket(&section_data_buffer[start..end], security_key)?;

        Ok(bag)
    }

    /// Helper function to decrypt pocket data using the security key.
    ///
    /// Each pocket entry consists of:
    /// - First 2 bytes: Item ID (u16)
    /// - Last 2 bytes: Quantity (u16, XORed with the security key)
    fn decrypt_pocket(data: &[u8], security_key: u16) -> Result<Vec<(String, u16)>, SaveDataError> {
        let mut pocket = Vec::new();

        for chunk in data.chunks(4) {
            if chunk.len() < 4 {
                return Err(SaveDataError::InvalidDataLength {
                    expected: 4,
                    found: chunk.len(),
                });
            }

            let item_id = LittleEndian::read_u16(&chunk[0..2]);
            let encrypted_quantity = LittleEndian::read_u16(&chunk[2..4]);
            let quantity = encrypted_quantity ^ security_key;

            let item_name = find_item(item_id as usize).unwrap_or_else(|_| "Nothing".to_string());
            pocket.push((item_name, quantity));
        }

        Ok(pocket)
    }

    /// Helper function to encrypt pocket data using the security key.
    ///
    /// # Arguments
    /// - `pocket`: A vector of tuples containing the item name and quantity.
    /// - `security_key`: The security key used for encryption.
    ///
    /// # Returns
    /// A byte vector containing the encrypted pocket data.
    fn encrypt_pocket(
        pocket: Vec<(String, u16)>,
        security_key: u16,
    ) -> Result<Vec<u8>, SaveDataError> {
        let mut encrypted_data = Vec::new();

        for (item_name, quantity) in pocket {
            let item_id = item_id_g3(&item_name).unwrap_or(0);
            let encrypted_quantity = quantity ^ security_key;

            encrypted_data.extend(&item_id.to_le_bytes());
            encrypted_data.extend(&encrypted_quantity.to_le_bytes());
        }

        Ok(encrypted_data)
    }

    pub fn raw_data(&self) -> Vec<u8> {
        self.data.to_vec()
    }

    fn init_pc_buffer(&mut self) {
        let current_save = self.current_save();

        let range = 5..=13;

        // Read all the Sections that hold the pc buffer from PCBufferA to PCbufferI
        let mut sections: Vec<&Section> = current_save
            .iter()
            .filter(|section| range.contains(&section.id(&self.data).into()))
            .collect();

        sections.sort_by(|a, b| {
            a.id(&self.data)
                .partial_cmp(&b.id(&self.data))
                .expect("Expected value but found None")
        });

        let sections: Vec<Section> = sections.iter().map(|section| **section).collect();

        // Store them into an array for easy access
        let mut pc_buffer: [Section; 9] = [Section::default(); 9];

        pc_buffer.copy_from_slice(sections.as_slice());

        self.pc_buffer = PCBuffer::new(pc_buffer, &self.data);
    }

    /// Determines the most recent save block (A or B) based on the save index.
    ///
    /// Each section in the save file contains a save index, but only the index in the last section is
    /// considered when determining the most recent save. The save index increases every time the game
    /// is saved, even when starting a new game.
    ///
    /// Returns a slice of sections corresponding to the most recent save block.
    fn current_save(&self) -> &[Section] {
        let save_index_a = self.game_save_a[0].save_index(&self.data);
        let save_index_b = self.game_save_b[0].save_index(&self.data);

        if save_index_a == u32::MAX {
            return &self.game_save_b;
        }
        if save_index_a > save_index_b {
            return &self.game_save_a;
        }

        &self.game_save_b
    }

    /// Retrieves the game code, which identifies the version of the game (e.g., Ruby, Sapphire, Emerald).
    ///
    /// The game code is stored in the Trainer Info section. For example:
    /// - `0x00000000`: Ruby/Sapphire
    /// - `0x00000001`: FireRed/LeafGreen
    /// - Any other value: Emerald
    ///
    /// Returns the game code or an error if the Trainer Info section is missing.
    fn get_game_code(&self) -> Result<u32, SaveDataError> {
        let section = self
            .get_section(SectionID::TrainerInfo)
            .ok_or(SaveDataError::SectionNotFound(SectionID::TrainerInfo))?;
        let section_data_buffer = section.data(&self.data);
        Ok(LittleEndian::read_u32(
            &section_data_buffer[0x00AC..0x00AC + 4],
        ))
    }

    fn get_section(&self, id: SectionID) -> Option<Section> {
        let current_save = self.current_save();

        current_save
            .iter()
            .find(|section| section.id(&self.data) == id)
            .copied()
    }

    /// Retrieves the high-level Trainer data (Name, ID, Money, Time, etc.)
    pub fn trainer(&self) -> Result<Trainer, SaveDataError> {
        let game_code = self.game_code();
        let version = match game_code {
            0 => GameVersion::RubySapphire,
            1 => GameVersion::FireRedLeafGreen,
            _ => GameVersion::Emerald,
        };

        let section0 = self
            .get_section(SectionID::TrainerInfo)
            .ok_or(SaveDataError::SectionNotFound(SectionID::TrainerInfo))?;
        let data0 = section0.data(&self.data);

        // Name (0x00 - 0x07)
        let name_bytes = &data0[0x00..0x08]; // 7 chars + terminator
        let name = name_bytes
            .iter()
            .take_while(|&&c| c != 0xFF)
            .map(|&c| get_char(c as usize))
            .collect::<String>();

        // Gender (0x08)
        let gender = if data0[0x08] == 1 {
            Gender::F
        } else {
            Gender::M
        };

        // ID (0x0A - 0x0E)
        let mut id_bytes = [0u8; 4];
        id_bytes.copy_from_slice(&data0[0x0A..0x0E]);
        let id = TrainerID::from(id_bytes);

        // Time Played (0x0E - 0x13)
        let time_played = TimePlayed::from_bytes(&data0[0x0E..0x13]);

        let section1 = self
            .get_section(SectionID::TeamItems)
            .ok_or(SaveDataError::SectionNotFound(SectionID::TeamItems))?;
        let data1 = section1.data(&self.data);

        // Money Offset: FRLG = 0x0290, Others = 0x0490
        let money_offset = if game_code == 1 { 0x0290 } else { 0x0490 };

        let encrypted_money = LittleEndian::read_u32(&data1[money_offset..money_offset + 4]);
        let money = encrypted_money ^ self.security_key();

        Ok(Trainer {
            name,
            gender,
            id,
            time_played,
            money,
            game_version: version,
            security_key: self.security_key(),
        })
    }

    /// Saves the modified Trainer struct back to the file.
    /// Updates both Section 0 (Info) and Section 1 (Money).
    pub fn save_trainer(&mut self, trainer: &Trainer) -> Result<(), SaveDataError> {
        let game_code = self.game_code();

        let section0 = self
            .get_section(SectionID::TrainerInfo)
            .ok_or(SaveDataError::SectionNotFound(SectionID::TrainerInfo))?;
        let data0 = section0.data_mut(&mut self.data);

        // Name
        let encoded_name: Vec<u8> = trainer
            .name
            .chars()
            .map(|c| get_code(&c.to_string()))
            .collect();
        // Pad with 0xFF (Terminator) then 0x00
        let mut final_name = [0x00u8; 8];
        for (i, &b) in encoded_name.iter().take(7).enumerate() {
            final_name[i] = b;
        }
        if encoded_name.len() < 7 {
            *final_name
                .get_mut(encoded_name.len())
                .ok_or(SaveDataError::InvalidOffset(encoded_name.len()))? = 0x00;
        }
        data0
            .get_mut(0x00..0x08)
            .ok_or(SaveDataError::InvalidRange(0x00..0x08))?
            .copy_from_slice(&final_name);

        // Gender
        *data0
            .get_mut(0x08)
            .ok_or(SaveDataError::InvalidOffset(0x08))? =
            if trainer.gender == Gender::F { 1 } else { 0 };

        // ID
        let id_bytes: Vec<u8> = trainer.id.into();
        data0
            .get_mut(0x0A..0x0E)
            .ok_or(SaveDataError::InvalidRange(0x0A..0x0E))?
            .copy_from_slice(&id_bytes);

        // Time
        data0
            .get_mut(0x0E..0x13)
            .ok_or(SaveDataError::InvalidRange(0x0E..0x13))?
            .copy_from_slice(&trainer.time_played.to_bytes());

        // Recalculate Section 0 Checksum
        section0.write_checksum(&mut self.data)?;

        let section1 = self
            .get_section(SectionID::TeamItems)
            .ok_or(SaveDataError::SectionNotFound(SectionID::TeamItems))?;

        // Need offset again
        let money_offset = if game_code == 1 { 0x0290 } else { 0x0490 };

        // Encrypt Money
        let encrypted_money = trainer.money ^ self.security_key();

        // We need a mutable reference to data again, but we can't hold two mutable borrows of `self.data`
        // So we re-acquire the slice for Section 1
        let data1 = section1.data_mut(&mut self.data);
        LittleEndian::write_u32(
            data1
                .get_mut(money_offset..money_offset + 4)
                .ok_or(SaveDataError::InvalidOffset(money_offset))?,
            encrypted_money,
        );

        // Recalculate Section 1 Checksum
        section1.write_checksum(&mut self.data)?;

        Ok(())
    }

    /// Internal helper to find the badge byte offset within Section 0 (Trainer Info).
    fn badge_offset(&self) -> Result<usize, SaveDataError> {
        let game_code = self.game_code();

        // The Badges are a single byte located in Section 0.
        // Offsets vary significantly by version:
        // 0 = Ruby/Sapphire
        // 1 = FireRed/LeafGreen
        // Others = Emerald

        match game_code {
            0 => Ok(0x0239), // Ruby/Sapphire
            1 => Ok(0x02B3), // FireRed/LeafGreen
            _ => Ok(0x0249), // Emerald
        }
    }

    /// Retrieves the Gym Badges flags.
    pub fn badges(&self) -> Result<GymBadges, SaveDataError> {
        let offset = self.badge_offset()?;

        let section = self
            .get_section(SectionID::TrainerInfo)
            .ok_or(SaveDataError::SectionNotFound(SectionID::TrainerInfo))?;

        let data = section.data(&self.data);

        if offset >= data.len() {
            return Err(SaveDataError::InvalidOffset(offset));
        }

        Ok(GymBadges::from_bytes([*data
            .get(offset)
            .ok_or(SaveDataError::InvalidOffset(offset))?]))
    }

    /// Writes the Gym Badges flags and updates the checksum.
    pub fn set_badges(&mut self, badges: GymBadges) -> Result<(), SaveDataError> {
        let offset = self.badge_offset()?;

        let section = self
            .get_section(SectionID::TrainerInfo)
            .ok_or(SaveDataError::SectionNotFound(SectionID::TrainerInfo))?;

        // Mutable access to Section 0
        let data = section.data_mut(&mut self.data);

        if offset >= data.len() {
            return Err(SaveDataError::InvalidOffset(offset));
        }

        let badges_data = data
            .get_mut(offset)
            .ok_or(SaveDataError::InvalidOffset(offset))?;

        *badges_data = badges.into_bytes()[0];

        // Update Checksum for Section 0
        section.write_checksum(&mut self.data)?;

        Ok(())
    }

    /// Reads the current number of Pokémon in the party.
    pub fn get_party_count(&self) -> Result<usize, SaveDataError> {
        let section = self
            .get_section(TEAM_SECTION_ID)
            .ok_or(SaveDataError::SectionNotFound(TEAM_SECTION_ID))?;
        let data = section.data(&self.data);

        let count = *data
            .get(PARTY_COUNT_OFFSET)
            .ok_or(SaveDataError::InvalidOffset(PARTY_COUNT_OFFSET))? as usize;
        if count > PARTY_SIZE {
            return Err(SaveDataError::InvalidDataLength {
                expected: 6,
                found: count,
            });
        }
        Ok(count)
    }
}
